### ISSUE TITLE
Worlds will not load when using this mod

### ISSUE THREAD

**Issue by XxShyW0lf** [ApacheTech-VintageStory-Mods/MinimalMapping#1]
30.7.2024 10:44:14 [Notification] Server logger started.
30.7.2024 10:44:14 [Notification] Game Version: v1.19.8 (Stable)
30.7.2024 10:44:14 [Event] Launching server...
30.7.2024 10:44:14 [Event] Server v1.19.8, network v1.19.8, api v1.19.0
30.7.2024 10:44:14 [Notification] Entering runphase Initialization
30.7.2024 10:44:14 [Event] Loading configuration...
30.7.2024 10:44:14 [Notification] Entering runphase Configuration
30.7.2024 10:44:14 [Notification] Loading savegame
30.7.2024 10:44:14 [Notification] Create new save game data. Playstyle: wildernesssurvival
30.7.2024 10:44:14 [Notification] Default spawn was set in serverconfig, resetting for safety.
30.7.2024 10:44:14 [Notification] Savegame C:\Users\XxShyWolf\AppData\Roaming\VintagestoryData\Saves\dark kingdom valley.vcdbs loaded
30.7.2024 10:44:14 [Notification] World size = 1024000 256 1024000
30.7.2024 10:44:14 [Notification] Start discovering assets
30.7.2024 10:44:14 [Notification] Found 1 base assets in category blocktypes
30.7.2024 10:44:14 [Notification] Found 0 base assets in category itemtypes
30.7.2024 10:44:14 [Notification] Found 25 base assets in category lang
30.7.2024 10:44:14 [Notification] Found 0 base assets in category patches
30.7.2024 10:44:14 [Notification] Found 24 base assets in category config
30.7.2024 10:44:14 [Notification] Found 0 base assets in category worldproperties
30.7.2024 10:44:14 [Notification] Found 48 base assets in category sounds
30.7.2024 10:44:14 [Notification] Found 95 base assets in category shapes
30.7.2024 10:44:14 [Notification] Found 133 base assets in category textures
30.7.2024 10:44:14 [Notification] Found 0 base assets in category recipes
30.7.2024 10:44:14 [Notification] Found 0 base assets in category worldgen
30.7.2024 10:44:14 [Notification] Found 3 base assets in category entities
30.7.2024 10:44:14 [Notification] Found 0 base assets in category compatibility
30.7.2024 10:44:14 [Notification] Found 0 base assets in category achievements
30.7.2024 10:44:14 [Notification] Found 329 base assets in total
30.7.2024 10:44:14 [Event] Building assets...
30.7.2024 10:44:14 [Notification] Entering runphase LoadAssets
30.7.2024 10:44:14 [Notification] Will search the following paths for mods:
30.7.2024 10:44:14 [Notification]     C:\Users\XxShyWolf\AppData\Roaming\Vintagestory\Mods
30.7.2024 10:44:14 [Notification]     C:\Users\XxShyWolf\AppData\Roaming\VintagestoryData\Mods
30.7.2024 10:44:15 [Notification] [StepUp-v1.2.0.cs] Successfully compiled 1 source files
30.7.2024 10:44:15 [Notification] Found 66 mods (62 disabled)
30.7.2024 10:44:15 [Notification] Mods, sorted by dependency: game, minimalmapping, creative, survival
30.7.2024 10:44:15 [Notification] Instantiated 111 mod systems from 4 enabled mods
30.7.2024 10:44:15 [Notification] External Origins in load order: modorigin@C:\Users\XxShyWolf\AppData\Roaming\Vintagestory\assets\creative\, modorigin@C:\Users\XxShyWolf\AppData\Roaming\Vintagestory\assets\survival\
30.7.2024 10:44:15 [Notification] Found 404 external assets in category blocktypes
30.7.2024 10:44:15 [Notification] Found 242 external assets in category itemtypes
30.7.2024 10:44:15 [Notification] Found 0 external assets in category lang
30.7.2024 10:44:15 [Notification] Found 9 external assets in category patches
30.7.2024 10:44:15 [Notification] Found 56 external assets in category config
30.7.2024 10:44:15 [Notification] Found 25 external assets in category worldproperties
30.7.2024 10:44:15 [Notification] Found 418 external assets in category sounds
30.7.2024 10:44:16 [Notification] Found 3636 external assets in category shapes
30.7.2024 10:44:16 [Notification] Found 5573 external assets in category textures
30.7.2024 10:44:16 [Notification] Found 363 external assets in category recipes
30.7.2024 10:44:16 [Notification] Found 478 external assets in category worldgen
30.7.2024 10:44:16 [Notification] Found 64 external assets in category entities
30.7.2024 10:44:16 [Notification] Found 0 external assets in category compatibility
30.7.2024 10:44:16 [Notification] Found 0 external assets in category achievements
30.7.2024 10:44:16 [Notification] Reloaded lang file with mod assets
30.7.2024 10:44:16 [Notification] Compatibility lib: 0 assets added, 0 assets replaced.
30.7.2024 10:44:16 [Notification] JsonPatch Loader: 24 patches total, successfully applied 24 patches, unmet conditions on 8 patches, no errors
30.7.2024 10:44:17 [Notification] Loaded 3335 unique items
30.7.2024 10:44:19 [Notification] Loaded 9312 unique blocks
30.7.2024 10:44:19 [Notification] Loaded 606 unique entities
30.7.2024 10:44:19 [Notification] BlockLoader: Entities, Blocks and Items loaded
30.7.2024 10:44:19 [Event] Remapping blocks and items...
30.7.2024 10:44:19 [Event] 8 cooking recipes loaded
30.7.2024 10:44:19 [Event] 677 crafting recipes loaded from 233 files
30.7.2024 10:44:19 [Event] 9 metal alloys loaded
30.7.2024 10:44:19 [Event] 241 smithing recipes loaded
30.7.2024 10:44:19 [Event] 55 clay forming recipes loaded
30.7.2024 10:44:19 [Event] 36 knapping recipes loaded
30.7.2024 10:44:20 [Event] 142 barrel recipes loaded
30.7.2024 10:44:20 [Notification] Entering runphase AssetsFinalize
30.7.2024 10:44:20 [Event] Server assets loaded, parsed, registered and finalized
30.7.2024 10:44:20 [Event] Initialising systems...
30.7.2024 10:44:20 [Notification] Entering runphase LoadGamePre
30.7.2024 10:44:20 [Notification] Reloaded 19 weather patterns, 5 wind patterns and 5 weather events
30.7.2024 10:44:20 [Notification] Started 96 systems on Server:
30.7.2024 10:44:20 [Notification]     Mod 'MinimalMapping_v2.0.1.zip' (minimalmapping):
30.7.2024 10:44:20 [Notification]         ApacheTech.VintageMods.MinimalMapping.Program
30.7.2024 10:44:20 [Notification]     Mod 'VSEssentials.dll' (game):
30.7.2024 10:44:20 [Notification]         Vintagestory.ServerMods.Core
30.7.2024 10:44:20 [Notification]         Vintagestory.GameContent.EntityPartitioning
30.7.2024 10:44:20 [Notification]         Vintagestory.GameContent.ErrorReporter
30.7.2024 10:44:20 [Notification]         Vintagestory.ServerMods.ModCompatiblityUtil
30.7.2024 10:44:20 [Notification]         Vintagestory.ServerMods.NoObf.ModJsonPatchLoader
30.7.2024 10:44:20 [Notification]         Vintagestory.Essentials.PathfindSystem
30.7.2024 10:44:20 [Notification]         Vintagestory.Essentials.PathFindDebug
30.7.2024 10:44:20 [Notification]         Vintagestory.Essentials.PathfindingAsync
30.7.2024 10:44:20 [Notification]         Vintagestory.ServerMods.JsonExport
30.7.2024 10:44:20 [Notification]         Vintagestory.ServerMods.ModBasicBlocksLoader
30.7.2024 10:44:20 [Notification]         Vintagestory.GameContent.ModSystemDormancyStateChecker
30.7.2024 10:44:20 [Notification]         Vintagestory.GameContent.ModSystemSyncHarvestableDropsToClient
30.7.2024 10:44:20 [Notification]         Vintagestory.GameContent.ModSystemEmotes
30.7.2024 10:44:20 [Notification]         Vintagestory.GameContent.LeafBlockDecay
30.7.2024 10:44:20 [Notification]         Vintagestory.GameContent.POIRegistry
30.7.2024 10:44:20 [Notification]         Vintagestory.GameContent.RoomRegistry
30.7.2024 10:44:20 [Notification]         Vintagestory.GameContent.WeatherSystemCommands
30.7.2024 10:44:20 [Notification]         Vintagestory.GameContent.WeatherSystemServer
30.7.2024 10:44:20 [Notification]         Vintagestory.GameContent.WorldMapManager
30.7.2024 10:44:20 [Notification]         Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader
30.7.2024 10:44:20 [Notification]         Vintagestory.ServerMods.LoadColorMaps
30.7.2024 10:44:20 [Notification]         Vintagestory.GameContent.ClothManager
30.7.2024 10:44:20 [Notification]         Vintagestory.ServerMods.GridRecipeLoader
30.7.2024 10:44:20 [Notification]     Mod 'VSSurvivalMod.dll' (survival):
30.7.2024 10:44:20 [Notification]         Vintagestory.ServerMods.GenTerra
30.7.2024 10:44:20 [Notification]         Vintagestory.ServerMods.GenSnowLayer
30.7.2024 10:44:20 [Notification]         Vintagestory.GameContent.ModSystemControlPoints
30.7.2024 10:44:20 [Notification]         Vintagestory.GameContent.SurvivalCoreSystem
30.7.2024 10:44:20 [Notification]         Vintagestory.ServerMods.GenTerraPostProcess
30.7.2024 10:44:20 [Notification]         Vintagestory.ServerMods.DebugSystem
30.7.2024 10:44:20 [Notification]         Vintagestory.ServerMods.UpgradeTasks
30.7.2024 10:44:20 [Notification]         Vintagestory.ServerMods.ChiselBlockBulkSetMaterial
30.7.2024 10:44:20 [Notification]         Vintagestory.ServerMods.ModSystemDetailModeSync
30.7.2024 10:44:20 [Notification]         Vintagestory.ServerMods.NpcControl
30.7.2024 10:44:20 [Notification]         Vintagestory.ServerMods.ModSystemTiledDungeonGenerator
30.7.2024 10:44:20 [Notification]         Vintagestory.ServerMods.GenFromHeightmap
30.7.2024 10:44:20 [Notification]         Vintagestory.ServerMods.GenMaps
30.7.2024 10:44:20 [Notification]         Vintagestory.ServerMods.GenRockStrataNew
30.7.2024 10:44:20 [Notification]         Vintagestory.ServerMods.GenHotSprings
30.7.2024 10:44:20 [Notification]         Vintagestory.ServerMods.GenCreatures
30.7.2024 10:44:20 [Notification]         Vintagestory.ServerMods.WgenCommands
30.7.2024 10:44:20 [Notification]         Vintagestory.GameContent.ModSystemExplosionAffectedStability
30.7.2024 10:44:20 [Notification]         Vintagestory.GameContent.MyceliumSystem
30.7.2024 10:44:20 [Notification]         Vintagestory.GameContent.ModsystemButterflySpawnCondsExtra
30.7.2024 10:44:20 [Notification]         Vintagestory.GameContent.ModSystemCatchCreature
30.7.2024 10:44:20 [Notification]         Vintagestory.GameContent.ModSystemGliding
30.7.2024 10:44:20 [Notification]         Vintagestory.GameContent.ClutterBookshelfUtil
30.7.2024 10:44:20 [Notification]         Vintagestory.GameContent.ScreenshakeToClientModSystem
30.7.2024 10:44:20 [Notification]         Vintagestory.GameContent.ModSystemResoArchiveCommands
30.7.2024 10:44:20 [Notification]         Vintagestory.GameContent.ResoArchivesSpawnConditions
30.7.2024 10:44:20 [Notification]         Vintagestory.GameContent.ModSystemAuction
30.7.2024 10:44:20 [Notification]         Vintagestory.GameContent.ModSystemBlockReinforcement
30.7.2024 10:44:20 [Notification]         Vintagestory.GameContent.Core
30.7.2024 10:44:20 [Notification]         Vintagestory.GameContent.CharacterSystem
30.7.2024 10:44:20 [Notification]         Vintagestory.GameContent.DialogueSystem
30.7.2024 10:44:20 [Notification]         Vintagestory.GameContent.FruitingSystem
30.7.2024 10:44:20 [Notification]         Vintagestory.GameContent.ModSystemCommandHandbook
30.7.2024 10:44:20 [Notification]         Vintagestory.GameContent.ModSystemTutorial
30.7.2024 10:44:20 [Notification]         Vintagestory.GameContent.ModSystemCorpseReturnTeleporter
30.7.2024 10:44:20 [Notification]         Vintagestory.GameContent.ModSystemNightVision
30.7.2024 10:44:20 [Notification]         Vintagestory.GameContent.ModJournal
30.7.2024 10:44:20 [Notification]         Vintagestory.GameContent.LiquidItemStackRenderer
30.7.2024 10:44:20 [Notification]         Vintagestory.GameContent.ModSystemStructureLocator
30.7.2024 10:44:20 [Notification]         Vintagestory.GameContent.ModLootRandomizer
30.7.2024 10:44:20 [Notification]         Vintagestory.GameContent.ModSystemRifts
30.7.2024 10:44:20 [Notification]         Vintagestory.GameContent.ModSystemRiftWeather
30.7.2024 10:44:20 [Notification]         Vintagestory.GameContent.ModSleeping
30.7.2024 10:44:20 [Notification]         Vintagestory.GameContent.ModSystemSupportBeamPlacer
30.7.2024 10:44:20 [Notification]         Vintagestory.GameContent.TeleporterManager
30.7.2024 10:44:20 [Notification]         Vintagestory.GameContent.ModTemperature
30.7.2024 10:44:20 [Notification]         Vintagestory.GameContent.SystemTemporalStability
30.7.2024 10:44:20 [Notification]         Vintagestory.GameContent.TemporalStabilityEffects
30.7.2024 10:44:20 [Notification]         Vintagestory.GameContent.ModSystemWearableStats
30.7.2024 10:44:20 [Notification]         Vintagestory.GameContent.ModSystemEditableBook
30.7.2024 10:44:20 [Notification]         Vintagestory.GameContent.Mechanics.MechanicalPowerMod
30.7.2024 10:44:20 [Notification]         Vintagestory.ServerMods.GenDungeons
30.7.2024 10:44:20 [Notification]         Vintagestory.ServerMods.GenDeposits
30.7.2024 10:44:20 [Notification]         Vintagestory.GameContent.GenStoryStructures
30.7.2024 10:44:20 [Notification]         Vintagestory.ServerMods.GenCaves
30.7.2024 10:44:20 [Notification]         Vintagestory.ServerMods.GenStructures
30.7.2024 10:44:20 [Notification]         Vintagestory.ServerMods.GenBlockLayers
30.7.2024 10:44:20 [Notification]         Vintagestory.ServerMods.GenPonds
30.7.2024 10:44:20 [Notification]         Vintagestory.ServerMods.GenStructuresPosPass
30.7.2024 10:44:20 [Notification]         Vintagestory.ServerMods.GenVegetationAndPatches
30.7.2024 10:44:20 [Notification]         Vintagestory.GameContent.RecipeRegistrySystem
30.7.2024 10:44:20 [Notification]         Vintagestory.ServerMods.GenRivulets
30.7.2024 10:44:20 [Notification]         Vintagestory.ServerMods.GenLightSurvival
30.7.2024 10:44:20 [Notification]         Vintagestory.ServerMods.RecipeLoader
30.7.2024 10:44:20 [Notification]         Vintagestory.GameContent.ModSystemOreMap
30.7.2024 10:44:20 [Notification]         Vintagestory.GameContent.ModSystemSnowballs
30.7.2024 10:44:20 [Notification]         Vintagestory.GameContent.TraderOutfits
30.7.2024 10:44:20 [Notification]         Vintagestory.GameContent.DisableRecipeRegisteringSystem
30.7.2024 10:44:20 [Notification]     Mod 'VSCreativeMod.dll' (creative):
30.7.2024 10:44:20 [Notification]         Vintagestory.ServerMods.Core
30.7.2024 10:44:20 [Notification]         Vintagestory.ServerMods.WorldEdit.WorldEdit
30.7.2024 10:44:20 [Notification]         Vintagestory.ServerMods.GenBlockLayersFlat
30.7.2024 10:44:20 [Notification]         Vintagestory.ServerMods.GenLightCreative
30.7.2024 10:44:20 [Notification] Server map set
30.7.2024 10:44:20 [Notification] Entering runphase LoadGame
30.7.2024 10:44:20 [Notification] Entering runphase WorldReady
30.7.2024 10:44:20 [Event] Starting world generators...
30.7.2024 10:44:21 [Notification] Sending server identification with remap False.  Server control privilege is True
30.7.2024 10:44:24 [Notification] Reloaded 35 tree generators
30.7.2024 10:44:24 [Event] Loading 7x7x8 spawn chunks...
30.7.2024 10:44:24 [Event] 0% (49 in queue)
30.7.2024 10:44:25 [Event] 0% (49 in queue)
30.7.2024 10:44:27 [Event] 0% (81 in queue)
30.7.2024 10:44:29 [Event] 0% (142 in queue)
30.7.2024 10:44:30 [Event] 0% (178 in queue)
30.7.2024 10:44:31 [Event] Begin game ticking...
30.7.2024 10:44:31 [Notification] Entering runphase RunGame
30.7.2024 10:44:31 [Notification] Server stop requested, begin shutdown sequence. Stop reason: Exception thrown by server during startup or process
30.7.2024 10:44:41 [Warning] Server suspend requested, but reached max wait time. Server is only partially suspended.
30.7.2024 10:44:41 [Notification] Entering runphase Shutdown
30.7.2024 10:44:41 [Notification] Defragmented listener lists
30.7.2024 10:44:41 [Event] Shutting down 6 server threads... 
30.7.2024 10:44:41 [Event] Killed console thread
30.7.2024 10:44:42 [Event] All threads gracefully shut down
30.7.2024 10:44:42 [Event] Doing last tick...
30.7.2024 10:44:42 [Event] Stopped the server!

**Comment by ApacheTech** [comment]
Hi, I will need your other log files as well. You can drag and drop them, and they'll upload as files.

This log file here shows everything working correctly.

**Comment by XxShyW0lf** [comment]
Oh interesting. What other log files do you need? Like the whole folder?

**Comment by ApacheTech** [comment]
Preferably, yes. You can zip the whole folder if you like.

**Comment by XxShyW0lf** [comment]
Ok

**Comment by XxShyW0lf** [comment]
[Logs.zip](https://github.com/user-attachments/files/16431745/Logs.zip)

**Comment by ApacheTech** [comment]
Fixed in v2.1.0
