### ISSUE TITLE
feat: control the draw distance for the world map, in relation to the player

### ISSUE THREAD

**Issue by ApacheTech** [ApacheTech-VintageStory-Mods/MinimalMapping#2]
[Thanks to @BanCannon for the suggestion]

Is it possible to modify the distance from player that the map is filled in as well? The default distance at which the map is filled in is so great that you can basically scout by UAV/Satillite. I would like to turn this down along with using the ability to disable X,Y,Z coordinates so that players have a functioning map of where they've been (finding your way back someplace you've been/marking findings in effect) but not so great that they use the map to scout.

It has been explained to me via discord that players maps being filled it directly related to their computer loading a chunk. I assume this means the functionality being asked about would be difficult to implement if even possible.

**Comment by ApacheTech** [comment]
**THEORY CRAFTING**

Fully independent of anything that the current `ChunkMapLayer` does, I can set a render limit (in chunks) via settings, and allow the user to change the limit. 

`void OnViewChangedClient(List<Vec2i> nowVisible, List<Vec2i> nowHidden)`

As a prefix to this method, if any chunk coord in `nowVisible` is outside of the user defined limit, then remove it, or add it to `nowHidden`.

A prefix on methods within `ChunkMapLayer`, such as `OnTick`, and `OnMapCmdRedraw` can cull `curVisibleChunks` of chunks outside the limit.

**Comment by ApacheTech** [comment]
Something along the lines of:

```csharp
    /// <summary>
    ///     Control Map Render Distance
    /// </summary>
    [HarmonyPrefix]
    [HarmonyPatch(typeof(ChunkMapLayer), "OnTick")]
    internal static void Harmony_ChunkMapLayer_OnTick_Prefix(ref HashSet<Vec2i> ___curVisibleChunks)
    {
        var renderDistance = MinimalWorldMapClientSystem.Settings.MapRenderDistance;
        var playerEntity = ApiEx.Client.World.Player.Entity;

        var cx = playerEntity.Pos.X / 32;
        var cz = playerEntity.Pos.Z / 32;
        var playerChunk = new Vec2i((int)cx, (int)cz);

        var outOfRange = ___curVisibleChunks.Where(p => p.ManhattenDistance(playerChunk) > renderDistance);
        ___curVisibleChunks = ___curVisibleChunks.Except(outOfRange).ToHashSet();
    }
```

**Comment by ApacheTech** [comment]
**OPTIONAL**

`IWorldMapSettings.WipeMapAtLogin`: _Wipe the client map whenever the player logs in._

This would delete the `.db` file each time the user logs in, forcing the file to be rebuilt from scratch. Waypoints would persist through logins, but would be stuck in the fog-of-war, unable to be pinned.

**Comment by ApacheTech** [comment]
**OPTIONAL**

`IWaypontsSettings.WipeWaypointsAtLogin`: _Wipe the player's waypoints whenever they logs in._

This would delete all the waypoints the user has saved on the server, whenever they log into the server.

**Comment by Nubb3r** [comment]
Hey, I'm new to Vintage Story and was looking for this exact feature.
Was this implemented in the end?
I can't find it being mentioned anywhere in the feature list of this mod.

The Long Dark has a similar system and there it is tied to world height.
So the higher you are, the larger the map drawing radius will be. Might be an idea?
